# Generated by Django 5.1.15 on 2026-02-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=5)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], default='', max_length=20)),
                ('referred_by', models.CharField(blank=True, default='', max_length=255)),
                ('allergies', models.TextField(blank=True, default='')),
                ('food_habits', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='', max_length=20)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('moderate', 'Moderate'), ('active', 'Active')], default='', max_length=20)),
                ('menstrual_history', models.TextField(blank=True, default='')),
                ('number_of_children', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vaccination_records', models.TextField(blank=True, default='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('medication', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Medical histories',
            },
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Family histories',
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', '-created_at'], name='patient_clinic_created'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['clinic', 'phone'], name='patient_clinic_phone'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('clinic', 'record_id'), name='unique_record_id_per_clinic'),
        ),
    ]
