# Generated by Django 5.1.15 on 2026-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        # No-op: date_of_birth already exists in 0001_initial
    ]
