# Generated by Django 5.1.15 on 2026-02-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_advice', models.TextField(blank=True, default='')),
                ('diet_advice_ta', models.TextField(blank=True, default='')),
                ('lifestyle_advice', models.TextField(blank=True, default='')),
                ('lifestyle_advice_ta', models.TextField(blank=True, default='')),
                ('exercise_advice', models.TextField(blank=True, default='')),
                ('exercise_advice_ta', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, default='')),
                ('follow_up_notes_ta', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinics.clinic')),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('OD', 'Once daily / \u0b92\u0bb0\u0bc1 \u0bae\u0bc1\u0bb1\u0bc8'), ('BD', 'Twice daily / \u0b95\u0bbe\u0bb2\u0bc8-\u0bae\u0bbe\u0bb2\u0bc8'), ('TDS', 'Thrice daily / \u0bae\u0bc2\u0ba9\u0bcd\u0bb1\u0bc1 \u0bae\u0bc1\u0bb1\u0bc8'), ('QID', 'Four times daily / \u0ba8\u0bbe\u0ba9\u0bcd\u0b95\u0bc1 \u0bae\u0bc1\u0bb1\u0bc8'), ('SOS', 'As needed / \u0ba4\u0bc7\u0bb5\u0bc8\u0baa\u0bcd\u0baa\u0b9f\u0bc1\u0bae\u0bcd\u0baa\u0bcb\u0ba4\u0bc1'), ('HS', 'At bedtime / \u0b87\u0bb0\u0bb5\u0bc1')], max_length=10)),
                ('frequency_tamil', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('instructions_ta', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name_plural': 'Procedure entries',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', '-created_at'], name='rx_clinic_created'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'follow_up_date'], name='rx_clinic_followup'),
        ),
    ]
