# Generated by Django 5.1.15 on 2026-03-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('prescriptions', '0002_medication_timing_medication_timing_tamil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_usages', to='pharmacy.medicine'),
        ),
    ]
