# Generated by Django 5.1.15 on 2026-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='timing',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='timing_tamil',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, choices=[('OD', 'Once daily / ஒரு முறை'), ('BD', 'Twice daily / காலை-மாலை'), ('TDS', 'Thrice daily / மூன்று முறை'), ('QID', 'Four times daily / நான்கு முறை'), ('SOS', 'As needed / தேவைப்படும்போது'), ('HS', 'At bedtime / இரவு')], default='', max_length=10),
        ),
    ]
