# Generated by Django 5.1.15 on 2026-02-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='instructions_ta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diet_advice_ta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='exercise_advice_ta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_notes_ta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='lifestyle_advice_ta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
