# Generated by Django 5.1.15 on 2026-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dilution_scale',
            field=models.CharField(blank=True, choices=[('C', 'Centesimal (C)'), ('X', 'Decimal (X)'), ('LM', 'LM Potency'), ('Q', 'Mother Tincture (Q)')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='medication',
            name='pellet_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='potency',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
