# Generated by Django 5.1.15 on 2026-03-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_dataexportaudit'),
        ('prescriptions', '0002_add_medication_potency_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedyFollowUpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('amelioration', 'Amelioration'), ('aggravation', 'Aggravation'), ('partial_response', 'Partial Response'), ('no_change', 'No Change'), ('return_of_old_symptoms', 'Return of Old Symptoms'), ('new_symptoms', 'New Symptoms')], max_length=30)),
                ('action_taken', models.CharField(choices=[('continue_same', 'Continue Same Remedy & Potency'), ('increase_potency', 'Increase Potency'), ('decrease_potency', 'Decrease Potency'), ('change_remedy', 'Change Remedy'), ('wait_and_watch', 'Wait and Watch'), ('antidote', 'Antidote')], max_length=20)),
                ('new_potency', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_followup_responses', to='clinics.clinic')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_followup_responses', to='prescriptions.prescription')),
                ('previous_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_followup_responses', to='prescriptions.prescription')),
                ('remedy_evaluated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_responses', to='prescriptions.medication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', '-created_at'], name='remedy_followup_clinic_date'), models.Index(fields=['prescription'], name='remedy_followup_prescription')],
            },
        ),
    ]
