# Generated by Django 5.1.15 on 2026-03-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_medication_medicine'),
        ('prescriptions', '0003_add_remedy_followup_response'),
    ]

    operations = [
    ]
