# Generated by Django 5.1.15 on 2026-02-28 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_dataexportaudit'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='clinics.clinic')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveSmallIntegerField()),
                ('start_day_number', models.PositiveSmallIntegerField()),
                ('end_day_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('replan_required', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='treatments.treatmentplan')),
            ],
            options={
                'ordering': ['block_number'],
            },
        ),
        migrations.CreateModel(
            name='DoctorActionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('block_completed', 'Block Completed'), ('review_requested', 'Review Requested')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctor_tasks', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_action_tasks', to='clinics.clinic')),
                ('treatment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tasks', to='treatments.treatmentblock')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_tasks', to='treatments.treatmentplan')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('session_date', models.DateField()),
                ('procedure_name', models.CharField(max_length=255)),
                ('medium_type', models.CharField(choices=[('oil', 'Oil'), ('powder', 'Powder'), ('other', 'Other')], default='other', max_length=20)),
                ('medium_name', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('execution_status', models.CharField(choices=[('planned', 'Planned'), ('done', 'Done'), ('not_done', 'Not Done')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treatments.treatmentblock')),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not Done')], max_length=20)),
                ('response_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
                ('review_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('treatment_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='treatments.treatmentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['clinic', 'status'], name='tplan_clinic_status'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['clinic', 'prescription'], name='tplan_clinic_rx'),
        ),
        migrations.AddIndex(
            model_name='treatmentblock',
            index=models.Index(fields=['treatment_plan', 'status'], name='tblock_plan_status'),
        ),
        migrations.AddIndex(
            model_name='treatmentblock',
            index=models.Index(fields=['start_date', 'end_date'], name='tblock_date_window'),
        ),
        migrations.AddConstraint(
            model_name='treatmentblock',
            constraint=models.UniqueConstraint(fields=('treatment_plan', 'block_number'), name='uniq_tblock_plan_number'),
        ),
        migrations.AddIndex(
            model_name='doctoractiontask',
            index=models.Index(fields=['clinic', 'status', 'task_type'], name='dtask_clinic_status_type'),
        ),
        migrations.AddIndex(
            model_name='doctoractiontask',
            index=models.Index(fields=['assigned_doctor', 'status'], name='dtask_doctor_status'),
        ),
        migrations.AddConstraint(
            model_name='doctoractiontask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('treatment_block', 'task_type'), name='uniq_open_doctor_task_per_block_type'),
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['treatment_block', 'execution_status'], name='tsession_block_exec'),
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['session_date'], name='tsession_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsession',
            constraint=models.UniqueConstraint(fields=('treatment_block', 'day_number'), name='uniq_tsession_block_day'),
        ),
        migrations.AddIndex(
            model_name='sessionfeedback',
            index=models.Index(fields=['therapist', '-created_at'], name='sfeedback_therapist_created'),
        ),
    ]
