# Generated by Django 5.1.15 on 2026-02-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appetite', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='', max_length=10)),
                ('appetite_notes', models.TextField(blank=True, default='')),
                ('bowel', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='', max_length=10)),
                ('bowel_notes', models.TextField(blank=True, default='')),
                ('micturition', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='', max_length=10)),
                ('micturition_notes', models.TextField(blank=True, default='')),
                ('sleep_quality', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], default='', max_length=10)),
                ('sleep_notes', models.TextField(blank=True, default='')),
                ('naa', models.TextField(blank=True, default='', help_text='Tongue examination')),
                ('niram', models.TextField(blank=True, default='', help_text='Complexion')),
                ('mozhi', models.TextField(blank=True, default='', help_text='Speech')),
                ('vizhi', models.TextField(blank=True, default='', help_text='Eyes')),
                ('nadi', models.TextField(blank=True, default='', help_text='Pulse - Prakruti, Vikruti, Upadosham')),
                ('mei', models.TextField(blank=True, default='', help_text='Touch/Body - heat, cold, normal')),
                ('muthiram', models.TextField(blank=True, default='', help_text='Urine - Neerkuri, Neikuri')),
                ('varmam', models.TextField(blank=True, default='', help_text='Varmam points assessment')),
                ('mental_state', models.TextField(blank=True, default='', help_text='Attitude/mental state observations')),
                ('chief_complaints', models.TextField(blank=True, default='')),
                ('history_of_present_illness', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('icd_code', models.CharField(blank=True, default='', max_length=20)),
                ('consultation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-consultation_date', '-created_at'],
            },
        ),
    ]
