# Generated by Django 5.1.15 on 2026-02-27 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['clinic', '-consultation_date'], name='consult_clinic_date'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['clinic', 'patient', '-consultation_date'], name='consult_clinic_pat_date'),
        ),
    ]
