# Generated by Django 5.1.15 on 2026-02-28 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_dataexportaudit'),
        ('consultations', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('clinic', 'patient', 'consultation_date'), name='unique_consultation_per_patient_day'),
        ),
    ]
