# Generated by Django 5.1.15 on 2026-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_unique_consultation_per_patient_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostic_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
