# Generated by Django 5.1.15 on 2026-02-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_migrate_envagai_to_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='mei',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='mozhi',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='muthiram',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='naa',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='nadi',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='niram',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='varmam',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='vizhi',
        ),
    ]
