# Generated by Django 4.2.29 on 2026-04-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_is_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='icd_code',
        ),
    ]
