# Generated by Django 5.1.15 on 2026-02-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('discipline', models.CharField(choices=[('siddha', 'Siddha'), ('ayurveda', 'Ayurveda'), ('yoga_naturopathy', 'Yoga & Naturopathy'), ('unani', 'Unani'), ('homeopathy', 'Homeopathy')], max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], default='A4', max_length=5)),
                ('primary_color', models.CharField(default='#2c5f2d', max_length=7)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('active_patient_limit', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
