# Generated by Django 5.1.15 on 2026-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_dataexportaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='ruthva_clinic_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
