# Generated by Django 5.1.15 on 2026-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_add_ruthva_clinic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='ruthva_clinic_id',
        ),
    ]
