# Generated by Django 5.1.15 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinic_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
    ]
