# Generated by Django 4.2.29 on 2026-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_add_letterhead_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
