# Generated by Django 4.2.29 on 2026-04-03 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_add_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='bottom_margin_mm',
            field=models.PositiveIntegerField(default=15, help_text='Bottom margin in mm for prescription PDF/print', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='clinic',
            name='google_review_url',
            field=models.URLField(blank=True, default='', help_text='Google Review URL for QR code on prescriptions'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='top_margin_mm',
            field=models.PositiveIntegerField(default=15, help_text='Top margin in mm for prescription PDF/print', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
