import { test, expect } from "@playwright/test";
const origin = "http://127.0.0.1:8796";
test("patient history saves, cancels, updates the overview and hides empty details", async ({ page, request }) => {
  page.on("pageerror", error => console.error(error.message));
  const { roles } = await (await request.get(`${origin}/__fixture`)).json();
  const headers = { Authorization: `Bearer ${roles.doctor.access}` };
  const response = await request.post(`${origin}/api/v1/patients/`, { headers, data: { name: "History Patient", age: 0, gender: "female", phone: "9876543210", number_of_children: 0 } });
  expect(response.ok()).toBe(true);
  const person = await response.json();
  await page.addInitScript(tokens => { localStorage.setItem("access_token", tokens.access); localStorage.setItem("refresh_token", tokens.refresh); localStorage.setItem("clinic_slug", "completion-test"); }, roles.doctor);
  await page.goto(`/patients/${person.id}`);
  await expect(page.getByRole("link", { name: /Confirm current medicines/ })).toBeVisible();
  await page.getByRole("link", { name: "Health history", exact: true }).click();
  await page.getByRole("button", { name: "Add or edit history" }).click();
  await page.getByRole("radio", { name: "None known", exact: true }).first().click();
  await page.getByRole("radio", { name: "None", exact: true }).click();
  await page.getByRole("button", { name: "Add medical history", exact: true }).click();
  await page.getByRole("textbox", { name: "Disease", exact: true }).fill("Asthma");
  await page.getByRole("textbox", { name: "Duration", exact: true }).fill("2 years");
  await page.getByRole("button", { name: "Save history", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Health history", exact: true })).toBeVisible();
  await expect(page.getByText("Check with the patient", { exact: true })).toHaveCount(0);
  await expect(page.getByText(/Medical history includes Asthma/)).toBeVisible();
  await page.getByRole("button", { name: "Add or edit history" }).click();
  await page.getByRole("textbox", { name: "Disease", exact: true }).fill("Unsaved condition");
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.reload();
  await expect(page.getByText("Asthma", { exact: true })).toBeVisible();
  await expect(page.getByText("Unsaved condition")).toHaveCount(0);
  await page.getByRole("link", { name: "Patient details", exact: true }).click();
  await expect(page.locator("dt").filter({ hasText: /^Email$/ })).toHaveCount(0);
  await expect(page.locator("dt").filter({ hasText: /^Number of children$/ })).toBeVisible();
  await expect(page.getByText("0 years", { exact: true })).toBeVisible();
});
