# Generated by Django 5.1.15 on 2026-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('prescription', 'Prescription Follow-up'), ('procedure', 'Procedure Follow-up')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('follow_up_date', models.DateField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('resend_email_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('reminder_type', 'object_id', 'follow_up_date'), name='unique_reminder_per_followup')],
            },
        ),
    ]
