# Generated by Django 5.1.15 on 2026-03-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_number',
        ),
    ]
