# Generated by Django 4.2.29 on 2026-03-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('discipline', models.CharField(choices=[('siddha', 'Siddha'), ('ayurveda', 'Ayurveda'), ('yoga_naturopathy', 'Yoga & Naturopathy'), ('unani', 'Unani'), ('homeopathy', 'Homeopathy')], max_length=30)),
                ('otp_code_hash', models.CharField(max_length=64)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
