# Generated by Django 5.1.15 on 2026-03-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_dataexportaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ta', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('kashayam', 'Kashayam / கஷாயம்'), ('choornam', 'Choornam / சூரணம்'), ('lehyam', 'Lehyam / லேகியம்'), ('tailam', 'Tailam / தைலம்'), ('arishtam', 'Arishtam / அரிஷ்டம்'), ('asavam', 'Asavam / ஆசவம்'), ('gulika', 'Gulika / குளிகை'), ('parpam', 'Parpam / பற்பம்'), ('chenduram', 'Chenduram / செந்தூரம்'), ('nei', 'Nei / நெய்'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('external', 'External Application'), ('other', 'Other'), ('mother_tincture', 'Mother Tincture (Q)'), ('trituration', 'Trituration (3X / 6X)'), ('centesimal', 'Centesimal Potency (C)'), ('lm_potency', 'LM Potency'), ('biochemic', 'Biochemic Tissue Salt')], max_length=30)),
                ('dosage_form', models.CharField(choices=[('ml', 'Millilitres (ml)'), ('g', 'Grams (g)'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('drops', 'Drops'), ('pinch', 'Pinch / சிட்டிகை'), ('spoon', 'Spoon / கரண்டி'), ('pellets', 'Pellets / Globules'), ('other', 'Other')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'name'), name='unique_medicine_name_per_clinic'), models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='medicine_stock_non_negative')],
            },
        ),
    ]
