# Generated by Django 5.1.15 on 2026-03-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0004_dataexportaudit'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='clinics.clinic')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ta', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('kashayam', 'Kashayam / கஷாயம்'), ('choornam', 'Choornam / சூரணம்'), ('lehyam', 'Lehyam / லேகியம்'), ('tailam', 'Tailam / தைலம்'), ('arishtam', 'Arishtam / அரிஷ்டம்'), ('asavam', 'Asavam / ஆசவம்'), ('gulika', 'Gulika / குளிகை'), ('parpam', 'Parpam / பற்பம்'), ('chenduram', 'Chenduram / செந்தூரம்'), ('nei', 'Nei / நெய்'), ('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('external', 'External Application'), ('other', 'Other'), ('mother_tincture', 'Mother Tincture (Q)'), ('trituration', 'Trituration (3X / 6X)'), ('centesimal', 'Centesimal Potency (C)'), ('lm_potency', 'LM Potency'), ('biochemic', 'Biochemic Tissue Salt')], max_length=30)),
                ('dosage_form', models.CharField(choices=[('ml', 'Millilitres (ml)'), ('g', 'Grams (g)'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('drops', 'Drops'), ('pinch', 'Pinch / சிட்டிகை'), ('spoon', 'Spoon / கரண்டி'), ('pellets', 'Pellets / Globules'), ('other', 'Other')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispensingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name_snapshot', models.CharField(max_length=255)),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispensing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispensingrecord')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_items', to='pharmacy.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('adjustment', 'Manual Adjustment'), ('dispense', 'Dispensed')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name_plural': 'Stock entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispensingrecord',
            index=models.Index(fields=['clinic', '-created_at'], name='disp_clinic_created'),
        ),
        migrations.AddIndex(
            model_name='dispensingrecord',
            index=models.Index(fields=['prescription'], name='disp_prescription'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['clinic', 'name'], name='med_clinic_name'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['clinic', 'category'], name='med_clinic_category'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['clinic', 'is_active'], name='med_clinic_active'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_medicine_name_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('current_stock__gte', 0)), name='medicine_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['medicine', '-created_at'], name='stock_med_created'),
        ),
    ]
